# Generated by Django 5.2 on 2025-04-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Restaurant Ming', max_length=100)),
                ('lugar', models.CharField(max_length=100)),
                ('cocina', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('precio_platos', models.CharField(max_length=50)),
                ('vista', models.CharField(max_length=100)),
                ('reservas', models.EmailField(max_length=254)),
            ],
        ),
    ]
