# Generated by Django 5.2 on 2025-04-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Restaurant Ming', max_length=100)),
                ('Lieu', models.CharField(max_length=100)),
                ('Cuisine', models.CharField(max_length=100)),
                ('Spécialité', models.CharField(max_length=100)),
                ('Prix_des_plats_principaux', models.CharField(max_length=50)),
                ('Vue', models.CharField(max_length=100)),
                ('Réservations', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameField(
            model_name='ejercicio1',
            old_name='cocina',
            new_name='Cuisine',
        ),
        migrations.RenameField(
            model_name='ejercicio1',
            old_name='especialidad',
            new_name='Lieu',
        ),
        migrations.RenameField(
            model_name='ejercicio1',
            old_name='precio_platos',
            new_name='Prix_des_plats_principaux',
        ),
        migrations.RenameField(
            model_name='ejercicio1',
            old_name='reservas',
            new_name='Réservations',
        ),
        migrations.RenameField(
            model_name='ejercicio1',
            old_name='lugar',
            new_name='Spécialité',
        ),
        migrations.RenameField(
            model_name='ejercicio1',
            old_name='vista',
            new_name='Vue',
        ),
    ]
