# Generated by Django 5.2 on 2025-05-11 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_ejercicio2_rename_cocina_ejercicio1_cuisine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio1',
            name='Réservations',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='ejercicio2',
            name='Réservations',
            field=models.CharField(),
        ),
    ]
