# Generated by Django 5.2 on 2025-05-13 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_ejercicio1_réservations_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio1',
            name='Réservations',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ejercicio2',
            name='Réservations',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Ejercicio1Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enviado', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.ejercicio1')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio1Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.ejercicio1historial')),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio1Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.ejercicio1historial')),
            ],
        ),
    ]
