# Generated by Django 5.2 on 2025-05-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_ejercicio1_réservations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio1',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ejercicio1',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ejercicio2',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ejercicio2',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
    ]
