# Generated by Django 5.2 on 2025-05-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_ejercicio1_comentario_ejercicio1_nota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio1historial',
            name='datos',
            field=models.JSONField(default=dict),
        ),
    ]
